docs:
   - all:
     - changed-files:
       - any-glob-to-any-file:
         - docs/en/docs/**
         - docs_src/**
       - all-globs-to-all-files:
         - '!readyapi/**'
         - '!pyproject.toml'

lang-all:
   - all:
     - changed-files:
       - any-glob-to-any-file:
         - docs/*/docs/**
       - all-globs-to-all-files:
         - '!docs/en/docs/**'
         - '!readyapi/**'
         - '!pyproject.toml'

internal:
   - all:
     - changed-files:
       - any-glob-to-any-file:
         - .github/**
         - scripts/**
         - .gitignore
         - .pre-commit-config.yaml
         - pdm_build.py
         - requirements*.txt
       - all-globs-to-all-files:
         - '!docs/*/docs/**'
         - '!readyapi/**'
         - '!pyproject.toml'
